### PR TITLE
Wrong detection of survivor in simple_cave_02 (local run)

### PR DESCRIPTION
**Pull request by m3d**
I collected locally some detection errors - first picture was from Simple Cave 02 and the second set is from Cave Circuit Practice 01 ... both cases are from the entrance area.

### CODE REVIEW

**Comment by zwn** [comment]
What is the easiest way to generate such an image set? I have a different world with a lots of false positives that I'd like to upload as well.

**Comment by m3d** [comment]
I use `subt/artifacts.py` with option `--debug2dir`, which saves all detector debug images into given directory.

**Comment by zwn** [comment]
Aha! Thanks. I got confused by this line:
```python
    parser.add_argument('filename', help='JPEG filename')
```
but that filename can actually be log filename.

**Comment by zwn** [comment]
Should I just add the files here or should I create a new PR? The false detections are for the ROPE artifact.

**Comment by m3d** [comment]
feel free to add it here (from my perspective) ... I created this PR as I do not know how to annotate "no artifact" ... if the number is < 30 I would add it here

**Comment by jisa** [comment]
Sorry for not spotting this earlier. I guess it is still relevant, right?

If so, the plan is to get the images in and let somebody add annotations, right?

**Comment by tajgr** [comment]
It is time to finish this PR.

**Review by jisa — APPROVED** [review]

**Pull request merged**
