### PR TITLE
qf-ver99, annotations and images

### PR DESCRIPTION
**Pull request by tajgr**

### CODE REVIEW

**Comment by m3d** [comment]
Whoow! I wonder when we reach the repository limit - good job :). I do not know how to check it - we should really introduce here some unittests. Is current detector failing on newly added images?

**Comment by m3d** [comment]
I wonder if some "drawing" script (input: images + annotation, output: directory with images with rectangles) would simplify the review? (i.e. to be sure that in none of 210 newly added images is misleading annotation?)

**Comment by jisa** [comment]
You could open it in the annotation tool. I must admit I do not do it. Occasionally, when I train a new model, I go through the data or specifically focus on training samples where the model struggles, which are most likely to be an error.

I normally make sure that Jakub has not accidentally obviously messed up with the json's and that he is not deleting older annotations without explicitly saying so.

**Review by jisa — APPROVED** [review]

**Comment by tajgr** [comment]
Thanks.

> would simplify the review?

yes, open the via.html and load the subt2020_project.json. I think, this is the best way.

**Pull request merged**
